version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: bank_loans
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-loans-network  # Add this line

  backend:
    build: 
      context: ./backend
    container_name: bank_loans_django
    restart: always
    depends_on: 
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - bank-loans-network
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - bank-loans-network  # Add this line
  
  frontend:
    container_name: bank-loans-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 on host to port 3000 in the container
    volumes:
      - ./frontend:/app  # Mount the current directory to /app in the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker
    depends_on:
      - backend
    networks:
      - bank-loans-network
  
volumes:
  postgres_data:
    driver: local

networks:
  bank-loans-network:
    driver: bridge  